INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('waran_z_komodo','Sid',14,'F','2006-07-24');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Hermiona',11,'M','2018-06-21');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_brunatny','Chicago',21,'F','2009-07-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('delfin','Czekoladka', 3,'F','2015-03-06');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ukwial','Freya',20,'F','2006-07-12');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zyrafa','Beethoven', 3,'F','2011-11-14');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wydra','Chelsea',17,'F','2008-08-07');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('tygrys','Leonardo',14,'M','2014-01-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('antylopa','Brutus',13,'F','2013-09-17');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('slon','Cola', 3,'F','2014-07-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('strus','Cytryn',14,'F','2011-03-02');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pelikan','Freya',19,'M','2006-03-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Jamajka',23,'F','2020-07-21');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kameleon','Budyn',18,'M','2019-10-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wegorz_morski','Gloria',19,'F','2012-01-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_polarny','Piorun',10,'F','2011-07-25');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zolw','Labradoryt', 4,'F','2012-11-11');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('slon','Jersey', 4,'M','2017-11-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ptasznik','Kotlet',10,'M','2010-01-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('antylopa','Sniezka',16,'F','2018-07-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('papuga','Labradoryt',10,'F','2019-07-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Szafir',20,'F','2013-12-14');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kameleon','Saba', 5,'F','2020-05-02');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ptasznik','Hannibal',15,'F','2019-10-28');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('konik_morski','Sztorm',16,'F','2009-03-06');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('glonojad','Bambi',22,'F','2010-04-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wydra','Gaja',10,'F','2007-10-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('slon','Chicago', 8,'F','2017-02-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('iguana','Bianka',23,'F','2012-07-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wilk','Teksas',17,'F','2007-07-25');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orangutan','Leon',23,'F','2017-07-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('konik_morski','Szafir', 4,'M','2018-07-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pelikan','Tarzan',14,'M','2008-04-21');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ukwial','Gaja', 2,'F','2013-06-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Gaja', 5,'M','2009-12-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zyrafa','Gloria',24,'F','2009-09-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('myszojelen','Kajtek',18,'F','2020-04-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('hipopotam','Hektor',25,'F','2007-02-12');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_polarny','Zeus', 3,'F','2009-10-21');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Szmaragd',19,'M','2016-10-24');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('myszojelen','Melon',14,'F','2019-08-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('flaming','Leon',11,'F','2015-08-24');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('szympans','Bursztyn', 7,'M','2005-04-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zolw','Mort',12,'F','2009-06-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('hipopotam','Hannibal',20,'M','2010-10-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orangutan','Gloria', 5,'F','2013-03-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('panda_mala','Frodo', 6,'M','2009-05-13');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('foka','Ozyrys',25,'F','2017-08-13');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('hiena','Czoko',13,'F','2008-12-12');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orka','Teksas',14,'F','2019-12-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('plaszczka','Hannibal',18,'M','2018-02-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orka','Granit',25,'F','2020-09-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lemur','Gaja', 1,'F','2019-07-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wydra','Robin',11,'F','2011-03-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('blazenek','Bursztyn',16,'F','2005-12-16');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pelikan','Sniezka', 1,'F','2011-12-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('blazenek','London',13,'F','2009-02-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('papuga','Czili',20,'F','2014-09-24');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('slon','Ryszard',24,'M','2019-01-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('glonojad','Wafel',15,'M','2013-03-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('nosorozec','Tarzan',20,'F','2015-10-10');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('papuga','Kajtek', 1,'M','2008-02-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_brunatny','Beethoven',10,'F','2015-02-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('alpaka','Bursztyn',20,'M','2010-02-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('krokodyl','Tarzan',16,'F','2008-04-24');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('alpaka','Jersey', 6,'M','2010-11-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('alpaka','Bursztyn',14,'M','2005-01-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wegorz_morski','Bianka',14,'M','2012-06-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Izyda', 1,'M','2019-11-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wydra','Tarzan', 4,'M','2017-10-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lew','Gerda',18,'M','2008-08-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('nosorozec','Rubin',13,'M','2012-07-11');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('panda_wielka','Blanka', 9,'F','2007-04-27');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('papuga','Brandy', 6,'M','2015-02-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Figa',12,'M','2010-08-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orka','Kajtek', 2,'F','2006-04-27');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ukwial','Hektor', 4,'F','2007-02-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Saba',16,'F','2015-04-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('goryl','Gloria', 3,'M','2008-10-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rekin','Beethoven', 2,'F','2017-11-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('foka','Jamajka', 7,'M','2011-09-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Baton', 8,'F','2018-12-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orangutan','Ikar', 8,'M','2020-06-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kozica','Leon', 1,'M','2020-01-10');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kangur','Saba',12,'M','2018-07-21');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('myszojelen','Leonardo',12,'M','2006-10-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('grzechotnik','Bonnie',23,'M','2008-01-11');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('slon','Gloria', 6,'F','2011-10-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('blazenek','Freya',25,'M','2007-12-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('hipopotam','Bona', 8,'F','2014-03-15');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ukwial','Lena',20,'F','2011-12-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kapibara','Hermiona',11,'M','2011-12-10');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wydra','Brylant',15,'M','2019-07-31');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('iguana','Brownie',20,'M','2016-03-21');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pingwin','Zeus',17,'F','2017-04-07');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_brunatny','Jersey', 4,'F','2010-07-28');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('boa','Chelsea', 7,'M','2013-01-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('konik_morski','Chelsea',14,'F','2013-11-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zyrafa','Blanka', 1,'M','2019-07-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kapibara','Brownie',15,'F','2005-02-28');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pelikan','Czekoladka', 5,'M','2013-01-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('panda_wielka','Max',21,'F','2015-09-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('flaming','Beethoven',14,'M','2019-08-31');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lew','Max', 9,'F','2020-04-27');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zolw','Kajtek', 5,'M','2011-07-13');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lemur','Bianka',15,'F','2015-10-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ptasznik','Nefryt',10,'M','2011-06-15');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Nefryt',25,'M','2018-03-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_polarny','Bianka',16,'M','2014-03-16');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('panda_wielka','Lena',22,'M','2008-03-10');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('boa','Wicher', 9,'M','2007-08-13');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('szympans','Sid', 2,'F','2008-02-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kameleon','Cezar',22,'F','2016-07-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lama','Lola', 7,'M','2016-05-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rekin','Labradoryt',16,'M','2013-02-13');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Jersey', 2,'F','2018-09-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('waran_z_komodo','Toffi',14,'M','2011-01-06');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('foka','Frodo', 3,'M','2012-08-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ukwial','Saba', 4,'F','2013-11-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('strus','Mars', 4,'F','2009-07-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wydra','Lena', 5,'M','2013-07-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('boa','Nel', 7,'F','2016-03-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pelikan','Opal', 4,'F','2005-07-28');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('plaszczka','Leonardo',11,'M','2017-11-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kameleon','Chicago',24,'M','2014-07-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('krokodyl','Topaz', 1,'M','2010-12-11');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Freya', 6,'F','2009-01-17');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('nosorozec','Freya',15,'M','2020-11-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zyrafa','Rambo',16,'M','2014-12-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orka','Szmaragd',16,'F','2017-06-25');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Jersey', 8,'F','2019-06-28');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ukwial','Cytryn',11,'M','2019-03-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lemur','Teksas',24,'F','2019-08-18');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('grzechotnik','Bonnie',13,'F','2013-06-07');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('anakonda','Mars',20,'F','2007-05-27');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('surykatka','Hannibal',17,'F','2020-02-18');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lama','Bambi',16,'F','2018-07-11');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('foka','Opal', 4,'M','2017-12-31');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('antylopa','Greta',21,'M','2014-06-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('hiena','Hektor',20,'M','2020-05-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('slon','Czoko',16,'M','2010-08-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('hiena','Brownie', 6,'M','2008-04-25');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Borowka',19,'M','2018-12-31');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lemur','Jamajka', 6,'M','2015-07-14');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('antylopa','Borowka',13,'F','2006-03-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('hipopotam','Szmaragd',21,'F','2020-04-02');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Czekoladka',22,'M','2015-02-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orka','Wicher',22,'F','2009-11-27');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('foka','Saba', 6,'F','2018-01-15');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_brunatny','Kiwi',21,'F','2012-10-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('boa','Napoleon',21,'M','2019-05-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_brunatny','Bambi',24,'F','2019-04-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('hiena','Blyskawica', 8,'F','2006-08-16');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('goryl','Gerda',16,'F','2012-04-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('anakonda','Bambi', 8,'M','2011-01-02');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orangutan','Czekoladka',25,'F','2008-07-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('glonojad','Zeus', 4,'M','2005-10-07');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zebra','Blanka',18,'F','2019-03-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('anakonda','Wicher',13,'M','2005-02-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Frytka',21,'F','2006-08-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('blazenek','Figa',12,'F','2006-07-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zyrafa','Wicher',25,'F','2009-05-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ptasznik','Paczek',12,'M','2013-07-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zebra','Jamajka',16,'M','2015-12-02');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Achilles', 9,'M','2015-02-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('goryl','Toffi',24,'M','2005-01-24');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kozica','Chicago', 7,'M','2016-10-10');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('orangutan','Melon', 3,'M','2013-10-07');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zebra','Kotlet',21,'F','2013-07-21');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ptasznik','Chelsea',12,'F','2020-09-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wegorz_morski','Cezar',24,'F','2016-09-07');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Nel', 5,'F','2012-03-17');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wilk','Melon', 8,'F','2019-06-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('boa','Tarzan',20,'M','2005-08-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Cezar', 8,'F','2014-07-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wilk','Granit',17,'M','2012-09-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('delfin','Kotlet',22,'M','2013-06-17');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zyrafa','Sid',13,'F','2014-05-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('myszojelen','Sniezka',11,'M','2012-10-12');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Piorun', 5,'M','2013-07-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('tygrys','Max',25,'M','2014-01-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kozica','Brutus',23,'M','2008-07-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pingwin','Ikar',12,'M','2015-08-25');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('foka','Wicher', 2,'F','2014-04-06');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lama','Sniezka',19,'M','2010-03-28');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('surykatka','Sid', 8,'M','2016-12-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('alpaka','Brylant',23,'M','2011-10-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Chelsea',15,'M','2006-07-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kameleon','Cola', 3,'M','2009-03-07');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('boa','Scooby',15,'M','2017-11-18');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('panda_wielka','Mozart',21,'M','2012-09-27');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('nosorozec','Nel',24,'M','2017-07-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('glonojad','Chelsea',12,'F','2007-11-13');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('szympans','Napoleon',22,'M','2015-04-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('strus','Paczek',11,'F','2009-05-11');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('okapi','Reks',11,'F','2014-10-15');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('alpaka','Sztorm', 8,'F','2013-12-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_brunatny','Bursztyn', 1,'M','2010-09-18');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('foka','Fortuna',24,'F','2008-08-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zyrafa','Sztorm', 7,'M','2012-04-14');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kapibara','Opal', 2,'M','2017-08-14');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('papuga','Izyda',11,'F','2014-01-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('leniwiec','Cytryna',10,'F','2006-06-25');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wilk','Scooby',17,'M','2017-11-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('dziobak','Bryza', 7,'M','2014-09-17');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('nosorozec','Brownie',15,'M','2016-05-29');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('slon','Greta',18,'F','2007-02-06');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('dziobak','Greta',10,'M','2005-07-11');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Wafel', 4,'F','2009-07-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Wicher',14,'M','2007-11-06');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('okapi','Frodo', 2,'M','2008-06-12');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_polarny','Opal', 1,'F','2011-10-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lemur','Bambi',20,'F','2016-11-24');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kangur','Wicher',12,'F','2010-04-25');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('panda_wielka','Wafel', 5,'F','2014-01-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Hektor', 8,'F','2009-11-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('delfin','Gaja',15,'F','2017-09-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Scooby',14,'F','2020-03-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Leon',19,'M','2006-07-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('antylopa','Hermiona',23,'F','2012-04-01');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('leniwiec','Tarzan', 5,'M','2010-05-12');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('wegorz_morski','Mort',21,'F','2020-08-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kangur','Ryszard', 6,'M','2007-11-22');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pelikan','Wafel',24,'F','2007-08-17');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('boa','Cytryna',24,'F','2018-04-14');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zolw','Blanka',16,'F','2016-08-20');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('koala','Lassie', 7,'M','2013-01-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('boa','Czekoladka',19,'M','2011-06-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('panda_wielka','Czili',10,'M','2013-06-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kapibara','Beethoven', 9,'M','2012-09-15');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('myszojelen','Sniezka',23,'M','2016-07-30');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rekin','Borowka',19,'M','2009-12-28');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('flaming','Lola',20,'F','2012-07-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('zolw','Scooby',20,'M','2019-08-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Wicher', 3,'M','2014-10-19');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lew','Max',25,'M','2010-02-04');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('strus','London', 1,'F','2009-03-09');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('pelikan','Sid',16,'F','2018-04-27');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('rys','Lassie',23,'F','2016-08-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('iguana','Sztorm',12,'F','2019-04-10');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('konik_morski','Mozart', 6,'M','2006-11-27');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lama','Brandy',24,'F','2009-03-05');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('lemur','Cytryn',11,'F','2010-02-26');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('ptasznik','Diament', 9,'M','2011-04-03');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('gepard','Cezar',22,'F','2018-07-23');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('grzechotnik','Kiwi', 9,'M','2015-01-06');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('szympans','Teksas', 4,'F','2014-05-21');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('szympans','Gloria',22,'M','2009-08-08');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('niedzwiedz_polarny','Teksas', 8,'F','2009-12-10');
INSERT INTO zwierzeta(gatunek, imie, id_opiekuna, plec, data_urodzenia) VALUES ('kozica','Kajtek',15,'F','2011-07-07');
